apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: post-service-ingress
  namespace: post-service-dev
  labels:
    app: post-service
    environment: development
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: post-service-dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: post-service
                port:
                  number: 80
