apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: post-service-dev
type: Opaque
data:
  # postgres (base64 encoded)
  POSTGRES_USER: cG9zdGdyZXM=
  # postgres (base64 encoded)  
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # postservice (base64 encoded)
  POSTGRES_DB: cG9zdHNlcnZpY2U=